### ISSUE TITLE
Encoding / CID Problem?

### ISSUE THREAD

**Issue by jacobfriedman** [daviddahl/wut#19]
on  ```node signal-server/server.js``` I get 
```
Signaling server running at /ip4/0.0.0.0/tcp/15555/ws/p2p-webrtc-star
(node:49766) UnhandledPromiseRejectionWarning: Error: Code 249728983 not found
    at Object.exports.getCodec (/home/jacob/projects/wut/node_modules/multicodec/src/index.js:64:11)
    at new CID (/home/jacob/projects/wut/node_modules/cids/src/index.js:82:33)
    at new CID (/home/jacob/projects/wut/node_modules/class-is/index.js:15:17)
    at mh2buf (/home/jacob/projects/wut/node_modules/multiaddr/src/convert.js:130:14)
    at Function.convertToBuffer [as toBuffer] (/home/jacob/projects/wut/node_modules/multiaddr/src/convert.js:76:14)
    at /home/jacob/projects/wut/node_modules/multiaddr/src/codec.js:96:35
    at Array.map (<anonymous>)
    at stringTuplesToTuples (/home/jacob/projects/wut/node_modules/multiaddr/src/codec.js:90:17)
    at stringToBuffer (/home/jacob/projects/wut/node_modules/multiaddr/src/codec.js:182:13)
    at Object.fromString (/home/jacob/projects/wut/node_modules/multiaddr/src/codec.js:189:10)
(node:49766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:49766) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Trying to debug this is a mess (I was also configuring webrtc-star just as you had when I saw your issues on it). Thinking your config would work as I envisioned ours architected (we're working on p2p-prolog), I still end up with more gotchas.

I'd love to hear back from you to see if this actually works based on some breaking changes that keep happening with webrtc-star. Unfortunately if we don't make any headway with libp2p we may have to simply go with Humblenet or just plain wrtc.

**Comment by daviddahl** [comment]
Just want to make sure you saw this: https://github.com/daviddahl/wut/blob/master/signal-server/README.md

I am trying to test my signaling server and will comment futher

**Comment by daviddahl** [comment]
Ok, so I was debugging things via this environment var: `DEBUG=libp2p:*` 

You can narrow down things by module in libp2p

**Comment by daviddahl** [comment]
Lemme know if you want to try and debug things via a real time session. I can give you my signaling server IP address and CID.

**Comment by jacobfriedman** [comment]
Yeah, if you have some time today it would be great. I have an aws instance
which doesn't work, same with local signalling server on. Peers get
discovered but when sending messages there's no response probably because
of the encoding problem in the stream.

**Comment by daviddahl** [comment]
I will try to be available but may not be until monday morning due to being off the grid.

**Comment by jacobfriedman** [comment]
Ok. In the meanwhile since I haven't gotten the web RTC star working in
about four different environments I'm going to start examining sea
libraries since I'm building for a WASM. No rush, no I am still interested.
 Thanks again for your help and congratulations on this supreme project

**Comment by jacobfriedman** [comment]
Hey, did you ever have a look at debugging the issue?

**Comment by daviddahl** [comment]
> Hey, did you ever have a look at debugging the issue?

Not yet. Will do so as soon as possible.

**Comment by jacobfriedman** [comment]
I've moved to use the wrtc star image as a base (p2p-prolog) - but am still
interested as your config is well-suited. Good luck

**Comment by jacobfriedman** [comment]
https://github.com/ipfs-shipyard/ipfs-pubsub-room/pull/81/commits
This may help you on your way...
